services:
  # Capa 1: El Escudo (Nginx)
  nginx:
    image: nginx:alpine
    container_name: ghi_web
    restart: always #alta disponibilidad
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./html:/var/www/html
    networks:
      - ghi_network
    depends_on:
      - api

  # Capa 2: La Lógica (Tu Backend)
  api:
    build:  # O la imagen que estés usando
      context: ./backend #<---Aqui le dices que el Dockerfile está en la carpeta de backend
      dockerfile: Dockerfile
    container_name: ghi_app
    restart: always #<-- alta disponibilidad
    env_file: .env
    volumes:
      - ./html:/var/www/html
    networks:
      - ghi_network
    depends_on:
      - db

  # Capa 3: Los Datos (MySQL para tu sistema de ventas)
  db:
    image: mysql:5.7
    container_name: ghi_db
    restart: always #<-- alta disponibilidad
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d #linea de seguridad DB
    networks:
      - ghi_network


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "${PORTAINER}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - ghi_network #<--agregado para que este en la misma red

networks:
  ghi_network:
    driver: bridge

volumes:
  db_data:
  portainer_data:
