version: '3.8'

services:
  backend-api:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"

  proxy-nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - backend-api
