services:
  # Capa 1: El Escudo (Nginx)
  nginx:
    image: nginx:alpine
    container_name: ghi_web
    restart: always #alta disponibilidad
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./html:/var/www/html
    networks:
      - ghi_network
    depends_on:
      - api

  # Capa 2: La Lógica (Tu Backend)
  api:
    build:  # O la imagen que estés usando
      context: ./backend #<---Aqui le dices que el Dockerfile está en la carpeta de backend
      dockerfile: Dockerfile
    container_name: ghi_app
    restart: always #<-- alta disponibilidad
    env_file: .env
    volumes:
      - ./html:/var/www/html
    networks:
      - ghi_network
    depends_on:
      - db

  # Capa 3: Los Datos (MySQL para tu sistema de ventas)
  db:
    image: mysql:5.7
    container_name: ghi_db
    restart: always #<-- alta disponibilidad
    env_file: .env
    environment:
      MYSQL_DATABASE: gh_imports_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - ghi_network

networks:
  ghi_network:
    driver: bridge

volumes:
  db_data:
